statefulset:
  statefulset_name: redis-stateful-set
  app_label: redis-app
  replicas: 3
  strategy_type: RollingUpdate
  affinity_key: works
  affinity_value: enable

spec:
  containers_name: redis-container
  containers_image: redis:5
  port: 6379

  resources_requests_memory: "64Mi"
  resources_requests_cpu: "250m"
  resources_limits_memory: "128Mi"
  resources_limits_cpu: "500m"

  volume_reddis_data: redis-data
  volume_reddis_data_mount: /data

  volume_reddis_config: redis-config
  volume_reddis_config_mount: /etc/redis
    

service:
  service_name: redis-sf-svc
  port: 6379
  target_port: 6379
  type: LoadBalancer

volumeClaimTemplates:
  volume_claim_name: redis-sf-pvc
  storage_class: app-data
  access_modes: "ReadWriteOnce"
  size: 1Gi