kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: data
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fsType: ext4
volumeBindingMode: Immediate
