apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.service_name }}
  labels:
    app: {{ .Values.statefulset.app_label}}
spec:
   ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
   type: {{ .Values.service.type }}
   selector:
    app: {{ .Values.statefulset.app_label}}
   externalName: my-samovar-postgres.com

 