apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-deployment
spec:
  selector:
    matchLabels:
      app: mysqldb-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqldb-deployment
    spec:
      containers:
        - image: mysql:8.0
          name: mysqldb-deployment
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root_pass
            - name: MYSQL_DATABASE
              value: test_db
            - name: MYSQL_USER
              value: test_user
            - name: MYSQL_PASSWORD
              value: user_pass
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysqldb-k3s-storage
              mountPath: /var/lib/mysql  
      volumes:
        - name: mysqldb-k3s-storage  #  volume name 
          persistentVolumeClaim:
            claimName: mysqldb-pv-claim-storage 
