apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqldb-pv-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k3s-data/mysql"
