apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: |
    argocdUrl: https://192.168.0.209:80
  service.webhook.discord: |
    url: https://discord.com/api/webhooks/1358075863995777214/VdwGIsm-Xmy8OK2uu-YDaGxTHpBU3pqDsnS6Xvev53gcMAorrvpg_0z3Ga9T3VmjdTff
    headers:
      - name: Content-Type
        value: application/json
  # Contains centrally managed global application subscriptions
  subscriptions: |
    - recipients:
        - discord
      triggers:
        - sync-operation-change
  trigger.sync-operation-change: |
    - when: app.status.operationState.phase in ['Succeeded']
      send: [app-deployed]
    - when: app.status.operationState.phase in ['Running']
      send: [app-sync-running]
    - when: app.status.operationState.phase in ['Unknown']
      send: [app-sync-status-unknown]
    - when: app.status.operationState.phase in ['Error', 'Failed']
      send: [app-sync-failed]
    - when: app.status.operationState.phase in ['Degraded']
      send: [app-health-degraded]
  template.app-created: |
    email:
      subject: Application {{.app.metadata.name}} has been created.
    message: Application {{.app.metadata.name}} has been created.
    teams:
      title: Application {{.app.metadata.name}} has been created.
  template.app-deleted: |
    email:
      subject: Application {{.app.metadata.name}} has been deleted.
    message: Application {{.app.metadata.name}} has been deleted.
    teams:
      title: Application {{.app.metadata.name}} has been deleted.
  template.app-deployed: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "embeds": [
              {
                "description": ":white_check_mark: Application {{.app.metadata.name}} is now running new version of deployments manifests."
              }
            ]
          }
  template.app-health-degraded: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "embeds": [
              {
                "description": ":exclamation: Application {{.app.metadata.name}} has degraded. Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}"
              }
            ]
          }
  template.app-sync-failed: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "embeds": [
              {
                "description": ":exclamation: The sync operation of application {{.app.metadata.name}} has failed at {{.app.status.operationState.finishedAt}} with the following error: {{.app.status.operationState.message}}\nSync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
              }
            ]
          }
  template.app-sync-running: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "embeds": [
              {
                "description": "The sync operation of application {{.app.metadata.name}} has started at {{.app.status.operationState.startedAt}}.\nSync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
              }
            ]
          }
  template.app-sync-status-unknown: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "embeds": [
              {
                "description": ":exclamation: Application {{.app.metadata.name}} sync is 'Unknown'.\nApplication details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}"
              }
            ]
          }
  template.app-sync-succeeded: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "embeds": [
              {
                "description": ":white_check_mark: Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.\nSync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
              }
            ]
          }
