deployment:
  deployment-name: test-deploy
  app-label: test-app
  replicas: 1
  strategy-type: RollingUpdate
  affinity-key: work
  affinity-value: true

spec:
  containers-name: test-container
  containers-image: nginx:alpine
  port: 80
  env:
    env-name: env-test-deploy
    env-values: balblabla

  resources-requests-memory: "64Mi"
  resources-requests-cpu: "250m"
  resources-limits-memory: "128Mi"
  resources-limits-cpu: "500m"

  volume-name: test-volume
  volumeMounts-mountPath: /usr/share/nginx/html/
    

service:
  service-name: test-svc
  port: 80
  target-port: 80
  type: LoadBalancer

persistentVolumeClaim:
  persistent-volume-claim-name: test-pvc
  storage-class: manual
  access-modes: ReadWriteMany
  size: 1Gi