apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-app-pv
  labels:
    type: local
    app: django
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/static"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-app-pvc
  labels:
    app: django
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: django-app-pv

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-cloud-todo-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-cloud-todo-list
  template:
    metadata:
      labels:
        app: django-cloud-todo-list
    spec:
      volumes:
        - name: django
          persistentVolumeClaim:
            claimName: django-app-pvc
      containers:
      - name: django-cloud-todo-list
        image: trickstermaster/cloud-todo-list-django_web:18.0
        ports:
          - containerPort: 8000
        imagePullPolicy: Always
        volumeMounts:
            - name: django
              mountPath: "/data/static"

---

apiVersion: v1
kind: Service
metadata:
  name: django-cloud-todo-list-svc
spec:
  selector:
    app: django-cloud-todo-list
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
