apiVersion: v1
kind: Service
metadata:
  name: django-cloud-todo-list-svc
spec:
  selector:
    app: django-cloud-todo-list
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-cloud-todo-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-cloud-todo-list
  template:
    metadata:
      labels:
        app: django-cloud-todo-list
    spec:
      containers:
      - name: django-cloud-todo-list
        image: trickstermaster/cloud-todo-list-django_web:18.0
        ports:
          - containerPort: 8000
        imagePullPolicy: Always
