apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pv-claim-storage
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rabbitmq-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq-deployment
    spec:
      containers:
        - image: rabbitmq:3-management
          name: rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 15672

          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /data
      volumes:
        - name: rabbitmq-storage  #  volume name
          persistentVolumeClaim:
            claimName: rabbitmq-pv-claim-storage
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  ports:
    - name: one
      port: 5672
      targetPort: 5672
    - name: too
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq-deployment
  type: LoadBalancer
