---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-helm-{{ .Release.Name }}
spec:
  selector:
    app: nginx-{{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
