apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        volumeMounts:
        - name: kubeconfig-volume
          mountPath: /var/jenkins_home/.kube  # Путь, где будет доступен kubeconfig
          subPath: kubeconfig.yaml
      volumes:
      - name: kubeconfig-volume
        secret:
          secretName: jenkins-kubeconfig
