apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://192.168.0.204:6443
    certificate-authority-data: /etc/kubernetes/pki/ca.crt
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: jenkins
    user: jenkins
  name: jenkins-context
current-context: jenkins-context
users:
- name: jenkins
  user:
    token: ${TOKEN}
