apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulset.statefulset_name}}
spec:
  selector:
    matchLabels:
      app: {{ .Values.statefulset.app_label}}
  replicas: {{ .Values.statefulset.replicas}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: {{ .Values.statefulset.strategy_type}} 
  template:
    metadata:
      labels:
        app: {{ .Values.statefulset.app_label}}
    spec:
      containers:
        - name: {{ .Values.spec.containers_name }}
          image: {{ .Values.spec.containers_image }}
          env:
           - name: MONGO_INITDB_ROOT_USERNAME
             value: {{ .Values.spec.env.env_user_name_values }}
           - name: MONGO_INITDB_ROOT_PASSWORD
             value: {{ .Values.spec.env.env_user_password_values }}
           - name: MONGO_INITDB_DATABASE
             value: {{ .Values.spec.env.env_db_name_values }}
          ports:
            - containerPort: {{ .Values.spec.port }}
          volumeMounts:
            # - mountPath: {{ .Values.spec.volume_name_init }}
            #   name: {{ .Values.spec.volumeMounts_mountPath_init }} 
            - mountPath: {{ .Values.spec.volume_name_db }}
              name: {{ .Values.spec.volumeMounts_mountPath_db }} 
          resources:
            requests:
              memory: {{ .Values.spec.resources_requests_memory }}
              cpu: {{ .Values.spec.resources_requests_cpu }}
            limits:
              memory: {{ .Values.spec.resources_limits_memory }}
              cpu: {{ .Values.spec.resources_limits_cpu }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.statefulset.affinity_key }}
                operator: In
                values:
                - {{ .Values.statefulset.affinity_value }}
  volumeClaimTemplates:
  # - metadata:
  #     name: {{ .Values.volumeClaimTemplates.volume_claim_name }}
  #   spec:
  #     accessModes: [ {{ .Values.volumeClaimTemplates.access_modes }} ]
  #     storageClassName: {{ .Values.volumeClaimTemplates.storage_class }}
  #     resources:
  #       requests:
  #         storage: {{ .Values.volumeClaimTemplates.size }}
  - metadata:
      name: {{ .Values.volumeClaimTemplates.volume_claim_name_db }}
    spec:
      accessModes: [ {{ .Values.volumeClaimTemplates.access_modes_db }} ]
      storageClassName: {{ .Values.volumeClaimTemplates.storage_class_dn }}
      resources:
        requests:
          storage: {{ .Values.volumeClaimTemplates.size_db }}
