---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-data
provisioner: driver.longhorn.io # указываем что нужно использовать ресурсы longhorn
allowVolumeExpansion: true # показываем что даный сторедж можно расширять 
parameters:
  numberOfReplicas: "1" # указываем количество реплик 
  fsType: xfs
  staleReplicaTimeout: "120" # 2 hours in minutes
  replicaAutoBalance: "best-effort" # равномерное распределение реплик  https://longhorn.io/docs/1.3.2/high-availability/auto-balance-replicas/
  # dataLocality: "best-effort" # указываем так чтобы под обращался к реплике которая находиться на этойже ноде https://longhorn.io/docs/1.3.2/high-availability/data-locality/
  fromBackup: ""
  nodeSelector: "jenkins"

