- name: Install Docker
  hosts: prometheus-grafana 
  become: yes

  tasks:
  - name: update ubuntu
    command: apt update

  tasks:
  - name: download docker sh
    command: curl -fsSL https://get.docker.com/ -o get-docker.sh

  tasks:
  - name: launch sh
    command: sh ./get-docker.sh

  tasks:
  - name: install compose
    command: apt-get install docker-compose -y

