apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.service_name }}
  labels:
    app: {{ .Values.statefulset.app_label}}
spec:
   ports:
    - name: {{ .Values.service.service_name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
    - name: {{ .Values.service.service_name_agent }}
      port: {{ .Values.service.port_agent }}
      targetPort: {{ .Values.service.target_port_agent }}
   type: {{ .Values.service.type }}
   selector:
    app: {{ .Values.statefulset.app_label}}

