deployment:
  deployment_name: neironkabbbot-deploy
  app_label: neironkabbbot-app
  replicas: 1
  strategy-type: RollingUpdate
  affinity_key: works
  affinity_value: enable

spec:
  containers_name: neironkabbbot-container
  containers_image: trickstermaster/neironkabbbot:3
  port: 80
  env:
    ENV_BOT_TOKEN: [eq
    ENV_AI_TOKEN: [eq
    ENV_PROXY: [eq

  resources_requests-memory: "64Mi"
  resources_requests-cpu: "250m"
  resources_limits-memory: "128Mi"
  resources_limits-cpu: "500m" 

    



